services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - project_a_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 3001:8080

volumes:
  project_a_data:
